//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ProductsDBModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ProductsDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ProductsDBEntities object using the connection string found in the 'ProductsDBEntities' section of the application configuration file.
        /// </summary>
        public ProductsDBEntities() : base("name=ProductsDBEntities", "ProductsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ProductsDBEntities object.
        /// </summary>
        public ProductsDBEntities(string connectionString) : base(connectionString, "ProductsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ProductsDBEntities object.
        /// </summary>
        public ProductsDBEntities(EntityConnection connection) : base(connection, "ProductsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblBUnit> tblBUnits
        {
            get
            {
                if ((_tblBUnits == null))
                {
                    _tblBUnits = base.CreateObjectSet<tblBUnit>("tblBUnits");
                }
                return _tblBUnits;
            }
        }
        private ObjectSet<tblBUnit> _tblBUnits;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblCable> tblCables
        {
            get
            {
                if ((_tblCables == null))
                {
                    _tblCables = base.CreateObjectSet<tblCable>("tblCables");
                }
                return _tblCables;
            }
        }
        private ObjectSet<tblCable> _tblCables;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblComponent> tblComponents
        {
            get
            {
                if ((_tblComponents == null))
                {
                    _tblComponents = base.CreateObjectSet<tblComponent>("tblComponents");
                }
                return _tblComponents;
            }
        }
        private ObjectSet<tblComponent> _tblComponents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblImage> tblImages
        {
            get
            {
                if ((_tblImages == null))
                {
                    _tblImages = base.CreateObjectSet<tblImage>("tblImages");
                }
                return _tblImages;
            }
        }
        private ObjectSet<tblImage> _tblImages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblSoftware> tblSoftwares
        {
            get
            {
                if ((_tblSoftwares == null))
                {
                    _tblSoftwares = base.CreateObjectSet<tblSoftware>("tblSoftwares");
                }
                return _tblSoftwares;
            }
        }
        private ObjectSet<tblSoftware> _tblSoftwares;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblBUnits EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblBUnits(tblBUnit tblBUnit)
        {
            base.AddObject("tblBUnits", tblBUnit);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblCables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblCables(tblCable tblCable)
        {
            base.AddObject("tblCables", tblCable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblComponents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblComponents(tblComponent tblComponent)
        {
            base.AddObject("tblComponents", tblComponent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblImages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblImages(tblImage tblImage)
        {
            base.AddObject("tblImages", tblImage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblSoftwares EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblSoftwares(tblSoftware tblSoftware)
        {
            base.AddObject("tblSoftwares", tblSoftware);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductsDBModel", Name="tblBUnit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblBUnit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblBUnit object.
        /// </summary>
        /// <param name="bUnitsID">Initial value of the BUnitsID property.</param>
        /// <param name="bUnitsName">Initial value of the BUnitsName property.</param>
        /// <param name="bUnitsType">Initial value of the BUnitsType property.</param>
        /// <param name="bUnitsDetails">Initial value of the BUnitsDetails property.</param>
        /// <param name="bUnitsStock">Initial value of the BUnitsStock property.</param>
        /// <param name="bUnitsPrice">Initial value of the BUnitsPrice property.</param>
        public static tblBUnit CreatetblBUnit(global::System.Int32 bUnitsID, global::System.String bUnitsName, global::System.String bUnitsType, global::System.String bUnitsDetails, global::System.Int32 bUnitsStock, global::System.Decimal bUnitsPrice)
        {
            tblBUnit tblBUnit = new tblBUnit();
            tblBUnit.BUnitsID = bUnitsID;
            tblBUnit.BUnitsName = bUnitsName;
            tblBUnit.BUnitsType = bUnitsType;
            tblBUnit.BUnitsDetails = bUnitsDetails;
            tblBUnit.BUnitsStock = bUnitsStock;
            tblBUnit.BUnitsPrice = bUnitsPrice;
            return tblBUnit;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BUnitsID
        {
            get
            {
                return _BUnitsID;
            }
            set
            {
                if (_BUnitsID != value)
                {
                    OnBUnitsIDChanging(value);
                    ReportPropertyChanging("BUnitsID");
                    _BUnitsID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BUnitsID");
                    OnBUnitsIDChanged();
                }
            }
        }
        private global::System.Int32 _BUnitsID;
        partial void OnBUnitsIDChanging(global::System.Int32 value);
        partial void OnBUnitsIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BUnitsName
        {
            get
            {
                return _BUnitsName;
            }
            set
            {
                OnBUnitsNameChanging(value);
                ReportPropertyChanging("BUnitsName");
                _BUnitsName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BUnitsName");
                OnBUnitsNameChanged();
            }
        }
        private global::System.String _BUnitsName;
        partial void OnBUnitsNameChanging(global::System.String value);
        partial void OnBUnitsNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BUnitsType
        {
            get
            {
                return _BUnitsType;
            }
            set
            {
                OnBUnitsTypeChanging(value);
                ReportPropertyChanging("BUnitsType");
                _BUnitsType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BUnitsType");
                OnBUnitsTypeChanged();
            }
        }
        private global::System.String _BUnitsType;
        partial void OnBUnitsTypeChanging(global::System.String value);
        partial void OnBUnitsTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BUnitsDetails
        {
            get
            {
                return _BUnitsDetails;
            }
            set
            {
                OnBUnitsDetailsChanging(value);
                ReportPropertyChanging("BUnitsDetails");
                _BUnitsDetails = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BUnitsDetails");
                OnBUnitsDetailsChanged();
            }
        }
        private global::System.String _BUnitsDetails;
        partial void OnBUnitsDetailsChanging(global::System.String value);
        partial void OnBUnitsDetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BUnitsStock
        {
            get
            {
                return _BUnitsStock;
            }
            set
            {
                OnBUnitsStockChanging(value);
                ReportPropertyChanging("BUnitsStock");
                _BUnitsStock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BUnitsStock");
                OnBUnitsStockChanged();
            }
        }
        private global::System.Int32 _BUnitsStock;
        partial void OnBUnitsStockChanging(global::System.Int32 value);
        partial void OnBUnitsStockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal BUnitsPrice
        {
            get
            {
                return _BUnitsPrice;
            }
            set
            {
                OnBUnitsPriceChanging(value);
                ReportPropertyChanging("BUnitsPrice");
                _BUnitsPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BUnitsPrice");
                OnBUnitsPriceChanged();
            }
        }
        private global::System.Decimal _BUnitsPrice;
        partial void OnBUnitsPriceChanging(global::System.Decimal value);
        partial void OnBUnitsPriceChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductsDBModel", Name="tblCable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblCable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblCable object.
        /// </summary>
        /// <param name="cablesID">Initial value of the CablesID property.</param>
        /// <param name="cablesName">Initial value of the CablesName property.</param>
        /// <param name="cablesType">Initial value of the CablesType property.</param>
        /// <param name="cablesDetails">Initial value of the CablesDetails property.</param>
        /// <param name="cablesStock">Initial value of the CablesStock property.</param>
        /// <param name="cablesPrice">Initial value of the CablesPrice property.</param>
        public static tblCable CreatetblCable(global::System.Int32 cablesID, global::System.String cablesName, global::System.String cablesType, global::System.String cablesDetails, global::System.Int32 cablesStock, global::System.Decimal cablesPrice)
        {
            tblCable tblCable = new tblCable();
            tblCable.CablesID = cablesID;
            tblCable.CablesName = cablesName;
            tblCable.CablesType = cablesType;
            tblCable.CablesDetails = cablesDetails;
            tblCable.CablesStock = cablesStock;
            tblCable.CablesPrice = cablesPrice;
            return tblCable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CablesID
        {
            get
            {
                return _CablesID;
            }
            set
            {
                if (_CablesID != value)
                {
                    OnCablesIDChanging(value);
                    ReportPropertyChanging("CablesID");
                    _CablesID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CablesID");
                    OnCablesIDChanged();
                }
            }
        }
        private global::System.Int32 _CablesID;
        partial void OnCablesIDChanging(global::System.Int32 value);
        partial void OnCablesIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CablesName
        {
            get
            {
                return _CablesName;
            }
            set
            {
                OnCablesNameChanging(value);
                ReportPropertyChanging("CablesName");
                _CablesName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CablesName");
                OnCablesNameChanged();
            }
        }
        private global::System.String _CablesName;
        partial void OnCablesNameChanging(global::System.String value);
        partial void OnCablesNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CablesType
        {
            get
            {
                return _CablesType;
            }
            set
            {
                OnCablesTypeChanging(value);
                ReportPropertyChanging("CablesType");
                _CablesType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CablesType");
                OnCablesTypeChanged();
            }
        }
        private global::System.String _CablesType;
        partial void OnCablesTypeChanging(global::System.String value);
        partial void OnCablesTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CablesDetails
        {
            get
            {
                return _CablesDetails;
            }
            set
            {
                OnCablesDetailsChanging(value);
                ReportPropertyChanging("CablesDetails");
                _CablesDetails = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CablesDetails");
                OnCablesDetailsChanged();
            }
        }
        private global::System.String _CablesDetails;
        partial void OnCablesDetailsChanging(global::System.String value);
        partial void OnCablesDetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CablesStock
        {
            get
            {
                return _CablesStock;
            }
            set
            {
                OnCablesStockChanging(value);
                ReportPropertyChanging("CablesStock");
                _CablesStock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CablesStock");
                OnCablesStockChanged();
            }
        }
        private global::System.Int32 _CablesStock;
        partial void OnCablesStockChanging(global::System.Int32 value);
        partial void OnCablesStockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CablesPrice
        {
            get
            {
                return _CablesPrice;
            }
            set
            {
                OnCablesPriceChanging(value);
                ReportPropertyChanging("CablesPrice");
                _CablesPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CablesPrice");
                OnCablesPriceChanged();
            }
        }
        private global::System.Decimal _CablesPrice;
        partial void OnCablesPriceChanging(global::System.Decimal value);
        partial void OnCablesPriceChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductsDBModel", Name="tblComponent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblComponent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblComponent object.
        /// </summary>
        /// <param name="componentsID">Initial value of the ComponentsID property.</param>
        /// <param name="componentsName">Initial value of the ComponentsName property.</param>
        /// <param name="componentsType">Initial value of the ComponentsType property.</param>
        /// <param name="componentsDetails">Initial value of the ComponentsDetails property.</param>
        /// <param name="componentsStock">Initial value of the ComponentsStock property.</param>
        /// <param name="componentsPrice">Initial value of the ComponentsPrice property.</param>
        public static tblComponent CreatetblComponent(global::System.Int32 componentsID, global::System.String componentsName, global::System.String componentsType, global::System.String componentsDetails, global::System.Int32 componentsStock, global::System.Decimal componentsPrice)
        {
            tblComponent tblComponent = new tblComponent();
            tblComponent.ComponentsID = componentsID;
            tblComponent.ComponentsName = componentsName;
            tblComponent.ComponentsType = componentsType;
            tblComponent.ComponentsDetails = componentsDetails;
            tblComponent.ComponentsStock = componentsStock;
            tblComponent.ComponentsPrice = componentsPrice;
            return tblComponent;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ComponentsID
        {
            get
            {
                return _ComponentsID;
            }
            set
            {
                if (_ComponentsID != value)
                {
                    OnComponentsIDChanging(value);
                    ReportPropertyChanging("ComponentsID");
                    _ComponentsID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ComponentsID");
                    OnComponentsIDChanged();
                }
            }
        }
        private global::System.Int32 _ComponentsID;
        partial void OnComponentsIDChanging(global::System.Int32 value);
        partial void OnComponentsIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ComponentsName
        {
            get
            {
                return _ComponentsName;
            }
            set
            {
                OnComponentsNameChanging(value);
                ReportPropertyChanging("ComponentsName");
                _ComponentsName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ComponentsName");
                OnComponentsNameChanged();
            }
        }
        private global::System.String _ComponentsName;
        partial void OnComponentsNameChanging(global::System.String value);
        partial void OnComponentsNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ComponentsType
        {
            get
            {
                return _ComponentsType;
            }
            set
            {
                OnComponentsTypeChanging(value);
                ReportPropertyChanging("ComponentsType");
                _ComponentsType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ComponentsType");
                OnComponentsTypeChanged();
            }
        }
        private global::System.String _ComponentsType;
        partial void OnComponentsTypeChanging(global::System.String value);
        partial void OnComponentsTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ComponentsDetails
        {
            get
            {
                return _ComponentsDetails;
            }
            set
            {
                OnComponentsDetailsChanging(value);
                ReportPropertyChanging("ComponentsDetails");
                _ComponentsDetails = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ComponentsDetails");
                OnComponentsDetailsChanged();
            }
        }
        private global::System.String _ComponentsDetails;
        partial void OnComponentsDetailsChanging(global::System.String value);
        partial void OnComponentsDetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ComponentsStock
        {
            get
            {
                return _ComponentsStock;
            }
            set
            {
                OnComponentsStockChanging(value);
                ReportPropertyChanging("ComponentsStock");
                _ComponentsStock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ComponentsStock");
                OnComponentsStockChanged();
            }
        }
        private global::System.Int32 _ComponentsStock;
        partial void OnComponentsStockChanging(global::System.Int32 value);
        partial void OnComponentsStockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ComponentsPrice
        {
            get
            {
                return _ComponentsPrice;
            }
            set
            {
                OnComponentsPriceChanging(value);
                ReportPropertyChanging("ComponentsPrice");
                _ComponentsPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ComponentsPrice");
                OnComponentsPriceChanged();
            }
        }
        private global::System.Decimal _ComponentsPrice;
        partial void OnComponentsPriceChanging(global::System.Decimal value);
        partial void OnComponentsPriceChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductsDBModel", Name="tblImage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblImage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblImage object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="extension">Initial value of the Extension property.</param>
        /// <param name="altText">Initial value of the AltText property.</param>
        public static tblImage CreatetblImage(global::System.Int32 id, global::System.String extension, global::System.String altText)
        {
            tblImage tblImage = new tblImage();
            tblImage.Id = id;
            tblImage.Extension = extension;
            tblImage.AltText = altText;
            return tblImage;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Extension
        {
            get
            {
                return _Extension;
            }
            set
            {
                OnExtensionChanging(value);
                ReportPropertyChanging("Extension");
                _Extension = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Extension");
                OnExtensionChanged();
            }
        }
        private global::System.String _Extension;
        partial void OnExtensionChanging(global::System.String value);
        partial void OnExtensionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AltText
        {
            get
            {
                return _AltText;
            }
            set
            {
                OnAltTextChanging(value);
                ReportPropertyChanging("AltText");
                _AltText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AltText");
                OnAltTextChanged();
            }
        }
        private global::System.String _AltText;
        partial void OnAltTextChanging(global::System.String value);
        partial void OnAltTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private Nullable<global::System.Int32> _Width;
        partial void OnWidthChanging(Nullable<global::System.Int32> value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private Nullable<global::System.Int32> _Height;
        partial void OnHeightChanging(Nullable<global::System.Int32> value);
        partial void OnHeightChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductsDBModel", Name="tblSoftware")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSoftware : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblSoftware object.
        /// </summary>
        /// <param name="softwareID">Initial value of the SoftwareID property.</param>
        /// <param name="softwareName">Initial value of the SoftwareName property.</param>
        /// <param name="softwareType">Initial value of the SoftwareType property.</param>
        /// <param name="softwareDetails">Initial value of the SoftwareDetails property.</param>
        /// <param name="softwareStock">Initial value of the SoftwareStock property.</param>
        /// <param name="softwarePrice">Initial value of the SoftwarePrice property.</param>
        public static tblSoftware CreatetblSoftware(global::System.Int32 softwareID, global::System.String softwareName, global::System.String softwareType, global::System.String softwareDetails, global::System.Int32 softwareStock, global::System.Decimal softwarePrice)
        {
            tblSoftware tblSoftware = new tblSoftware();
            tblSoftware.SoftwareID = softwareID;
            tblSoftware.SoftwareName = softwareName;
            tblSoftware.SoftwareType = softwareType;
            tblSoftware.SoftwareDetails = softwareDetails;
            tblSoftware.SoftwareStock = softwareStock;
            tblSoftware.SoftwarePrice = softwarePrice;
            return tblSoftware;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SoftwareID
        {
            get
            {
                return _SoftwareID;
            }
            set
            {
                if (_SoftwareID != value)
                {
                    OnSoftwareIDChanging(value);
                    ReportPropertyChanging("SoftwareID");
                    _SoftwareID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SoftwareID");
                    OnSoftwareIDChanged();
                }
            }
        }
        private global::System.Int32 _SoftwareID;
        partial void OnSoftwareIDChanging(global::System.Int32 value);
        partial void OnSoftwareIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SoftwareName
        {
            get
            {
                return _SoftwareName;
            }
            set
            {
                OnSoftwareNameChanging(value);
                ReportPropertyChanging("SoftwareName");
                _SoftwareName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SoftwareName");
                OnSoftwareNameChanged();
            }
        }
        private global::System.String _SoftwareName;
        partial void OnSoftwareNameChanging(global::System.String value);
        partial void OnSoftwareNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SoftwareType
        {
            get
            {
                return _SoftwareType;
            }
            set
            {
                OnSoftwareTypeChanging(value);
                ReportPropertyChanging("SoftwareType");
                _SoftwareType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SoftwareType");
                OnSoftwareTypeChanged();
            }
        }
        private global::System.String _SoftwareType;
        partial void OnSoftwareTypeChanging(global::System.String value);
        partial void OnSoftwareTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SoftwareDetails
        {
            get
            {
                return _SoftwareDetails;
            }
            set
            {
                OnSoftwareDetailsChanging(value);
                ReportPropertyChanging("SoftwareDetails");
                _SoftwareDetails = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SoftwareDetails");
                OnSoftwareDetailsChanged();
            }
        }
        private global::System.String _SoftwareDetails;
        partial void OnSoftwareDetailsChanging(global::System.String value);
        partial void OnSoftwareDetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SoftwareStock
        {
            get
            {
                return _SoftwareStock;
            }
            set
            {
                OnSoftwareStockChanging(value);
                ReportPropertyChanging("SoftwareStock");
                _SoftwareStock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SoftwareStock");
                OnSoftwareStockChanged();
            }
        }
        private global::System.Int32 _SoftwareStock;
        partial void OnSoftwareStockChanging(global::System.Int32 value);
        partial void OnSoftwareStockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SoftwarePrice
        {
            get
            {
                return _SoftwarePrice;
            }
            set
            {
                OnSoftwarePriceChanging(value);
                ReportPropertyChanging("SoftwarePrice");
                _SoftwarePrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SoftwarePrice");
                OnSoftwarePriceChanged();
            }
        }
        private global::System.Decimal _SoftwarePrice;
        partial void OnSoftwarePriceChanging(global::System.Decimal value);
        partial void OnSoftwarePriceChanged();

        #endregion

    
    }

    #endregion

    
}
